### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [FBergeron/KankenFlashcard#2]
It'd be neat to have this app also distributed on F-Droid. https://f-droid.org/

Would you oppose this idea?

**Comment by FBergeron** [comment]
I don't oppose the idea but it's not a priority for now.  Eventually, I might take a look to that.  Thanks for the suggestion.

**Comment by nicolasmaia** [comment]
Perhaps @rudloff can take a look at whether it's possible to include in the catalog.

**Comment by Rudloff** [comment]
This will be a problem:
https://github.com/FBergeron/KankenFlashcard/blob/f59db511703e8413093c9d3cabd907d05b9f34dc/app/build.gradle#L35

We don't allow non-free libraries.
